#!/usr/bin/env bash
# transfer files !!!!!!    That is one way of publishing your website pages to your server. !!!!!!!

if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp some_page.html ubuntu@34.139.6.234:~/
fi