#!/usr/bin/env bash
# command line to intall nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw app list
sudo ufw enable
sudo ufw allow 'Nginx HTTPS'
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx Full'
sudo ufw status
sudo > /var/www/html/index.nginx-debian.html ; echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

