#!/usr/bin/env bash
# add a custom Nginx response header.
# shellcheck disable=SC2154
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i '11 a add_header X-Served-By $hostname always;' /etc/nginx/nginx.conf
sudo service nginx restart
sudo service nginx reload
